name: upstream-release-issue

on:
  workflow_dispatch: null
  schedule:
    # Scheduled everyday At 00:00
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: release-notifier-gh
        uses: maheshrayas/action-release-notifier@v2.1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          type: Github
          repo: 'https://github.com/koekeishiya/yabai'
          days: 1 #optional field, default 1 day, , make sure you set the cron appropriately, Example if you want to check for release once in 7 days, set days: 7 and cron schedule to run once in 7 days
          labels: 'release'
